### ISSUE TITLE
Branch and bound failure

### ISSUE THREAD

**Issue by SteveDiamond** [embotech/ecos-python#12]
Something is deeply wrong with the branch and bound interface. The following code fails, seeming to impose the boolean constraint on ``y`` instead of ``x``. I will try to look into this but this is a very serious bug. (Possibly in ECOS).
```
from cvxpy import *
y = Variable()
x = Bool()
prob = Problem(Minimize(x + y), [x >= 0.5, y == 0])
print prob.solve() # should be 1.0
print x.value
print y.value

# Solve using direct call to ECOS.
import ecos
import cvxpy.settings as s
data = prob.get_problem_data(ECOS_BB)
results_dict = ecos.solve(data[s.C], data[s.G], data[s.H],
                          data[s.DIMS], data[s.A], data[s.B],
                          verbose=True,
                          mi_verbose=True,
                          bool_vars_idx=data[s.BOOL_IDX],
                          int_vars_idx=data[s.INT_IDX])
print results_dict
```

**Comment by adomahidi** [comment]
Thanks for reporting this. Does this also happen when you call it directly from C or Matlab? I.e. is it an interface issue or a solver issue?

**Comment by SteveDiamond** [comment]
I don't know. I couldn't find a matlab interface for mixed integer problems and when I ran made and ran bb_test I got a segfault. Is bb_test supposed to work?

**Comment by SteveDiamond** [comment]
Ok I looked into this and it's an ECOS BB bug. It's a simple fix that I addressed in a PR.

**Comment by adomahidi** [comment]
Thanks, I merged the PR into master on the core ECOS branch, a new release will have to be created for this. Until then please pull commit be6280b9bd63a1db0562a761d8517fde232cd2a0 from github.com/embotech/ecos

**Comment by SteveDiamond** [comment]
Ok thanks! Can you please get a new release on PyPi soon though? This is a really bad bug that makes ECOS BB essentially unusable. I'm going to update my conda distribution of ECOS today with the commit you referenced but it would be good to have the latest version on PyPi too. It's not good that people have been using ECOS BB and sometimes getting incorrect results.
