### ISSUE TITLE
Verbosity cannot be disabled with the branch and bound solver.

### ISSUE THREAD

**Issue by Viech** [embotech/ecos-python#14]
Hello, when I solve a (mixed) integer problem with `verbose = False`, ECOS still produces output such as the following:
```
Iter	Lower Bound	Upper Bound	Gap
================================================
0 	38.05 		inf 		inf
1 	45.67 		55.00 		9.33
2 	46.85 		55.00 		8.15
3 	51.72 		55.00 		3.28
4 	54.19 		55.00 		0.81
5 	54.67 		55.00 		0.33
6 	54.94 		55.00 		0.06
7 	55.00 		55.00 		0.00
```
The branch and bound solver of ECOS supports setting verbosity as of https://github.com/embotech/ecos/commit/cc635e59feade2a5175b83d7d5aefc8d6151f36d, so I assume that the issue is rather in the Python interface.

I'd also be happy about a workaround in case the fix takes a while to enter a release.

**Comment by echu** [comment]
Hmm. Yeah, thats an issue with the interface. I dont know of an easy workaround (you could try to suppress stdout when the solver runs.

If you have time, feel free to submit a PR to fix this. I’ll try to find some time this week to release a patch.

**Comment by Viech** [comment]
Looking at the code I found that `mi_verbose` controls the output in question, it's just not documented anywhere where I had looked before. In particular it's missing [here](https://github.com/embotech/ecos-python/blob/master/src/ecosmodule.c#L119) and from the README.md.

I tried working around by redirecting stdout, but that didn't affect the printing done by the C part of ECOS.

**Comment by echu** [comment]
Ah, so just to confirm, the functionality exists, you just needed to find the right value to set? I'll update the README for this.

**Comment by Viech** [comment]
Yes, in addition to `verbose` I also had to set `mi_verbose` to zero to disable output also for mixed integer problems.

**Comment by echu** [comment]
Okay. Great. I updated the README and comments in the file you referenced to include this. I'll close the issue now. Feel free to re-open if you still have issues.
