### ISSUE TITLE
ecos.__version___ is wrong on ecos > 2.0.4

### ISSUE THREAD

**Issue by wkschwartz** [embotech/ecos-python#18]
Just did `pip install ecos` and `pip install "ecos >= 2.0.7rc2"` to receive, respectively, ecos==2.0.5 and ecos==2.0.7rc2. On both installations, I ran
```python
>>> import ecos
>>> ecos.__version__
'2.0.4'
```

**Comment by echu** [comment]
See, that's the kind of bug that (really) needs to be fixed. :)

Thanks for reporting.
