### ISSUE TITLE
Need a new pip release

### ISSUE THREAD

**Issue by SteveDiamond** [embotech/ecos-python#2]
This commit fixes an important issue in ECOS BB:

https://github.com/embotech/ecos/commit/bde8662bd85030bbf5288e868529f80e5fa8bdd0

I don't think it's in the ECOS on pip. Could you put out a new version that has this update? This may require bumping the ECOS version number.

**Comment by echu** [comment]
It's taken a couple months but we *just* released.

https://pypi.python.org/pypi/ecos/2.0.0
