### ISSUE TITLE
Incosistent Python API doc on embotech's website

### ISSUE THREAD

**Issue by aickley** [embotech/ecos-python#6]
[Embotech's web page on ECOS's Python API](https://www.embotech.com/ECOS/How-to-use/Python-API) mentions that `G` and `A` matrices should be in scipy's CSR format. In fact, the wrapper's preferred format is CSC which is clear from the code (if one supplies the arguments in CSR there is an additional conversion to CSC).

**Comment by adomahidi** [comment]
Thanks for pointing this out, we have corrected the embotech web page.

**Comment by RoyiAvital** [comment]
@adomahidi , The documentation actually still says CSR:

![image](https://github.com/embotech/ecos-python/assets/7347975/037b55b6-01a8-40c9-8716-142021b85d32)
