### ISSUE TITLE
`pip install ecos` fails when numpy is not already installed

### ISSUE THREAD

**Issue by ntezak** [embotech/ecos-python#8]
The setup.py script tries importing numpy and thus already causes an installation failure before any missing numpy dependency can be resolved.

**Comment by echu** [comment]
Ah, good point! Thanks for pointing this out.

**Comment by echu** [comment]
I dug a little bit, it's apparently not an easy fix. (Google "numpy bootstrap setup.py")

See [here](http://stackoverflow.com/questions/19919905/how-to-bootstrap-numpy-installation-in-setup-py) and you can read about how scipy does it transparently [here](https://github.com/scipy/scipy/blob/master/setup.py). It looks like there is no good, clean way to bootstrap numpy before building the Extension. The "best" solution pollutes a global `__builtins__` (python2; `builtins` in python3) variable, while also "building" numpy for commands as simple as `python setup.py --help`.

The following sequence of commands will work
```
pip install numpy
pip install ecos
```
But `pip install ecos` by itself will fail (if you don't have numpy).

Would it satisfy your use case if we print a helpful error message saying that you need to install numpy first with `pip install numpy`?

**Comment by ntezak** [comment]
Yeah, I could see how that is tricky. A warning/error message would definitely be helpful! Thanks for looking into it.

**Comment by echu** [comment]
I just merged in a PR that should address this. Hopefully have it released soon.

**Comment by wkschwartz** [comment]
Under Python 3.7 with pip 18.1 and setuptools 40.4.3 (win) and 39.0.1 (mac), `pip install "ecos >= 2.0.7rc2"` worked without a problem on both Windows 7 in the Visual Studio 2017 Build Tools Developer Command Prompt and on macOS. I had no issues with NumPy.

**Comment by echu** [comment]
I just released this, also with wheels. :)
